# Generated by Django 4.0.3 on 2022-03-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=50)),
                ('Number_of_rooms', models.CharField(max_length=10)),
                ('description', models.CharField(default='', max_length=250)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
