# Generated by Django 4.0.3 on 2022-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('multiple', 'Multiple')], max_length=20, null=True)),
                ('capacity', models.CharField(default='', max_length=3)),
                ('price', models.CharField(default='', max_length=5, null=True)),
                ('no_of_beds', models.CharField(default='', max_length=2)),
                ('vacancy', models.BooleanField(default=False)),
            ],
        ),
    ]
