# Generated by Django 4.0.2 on 2022-02-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_DOB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
