# Generated by Django 4.0.2 on 2022-03-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_profile',
            new_name='profile',
        ),
    ]
