# Generated by Django 4.0.2 on 2022-03-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_DOB',
            new_name='dob',
        ),
    ]
