# Generated by Django 4.0.3 on 2022-03-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_room_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='room_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
