# Generated by Django 4.0.3 on 2022-03-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_room_id_alter_payment_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
